name: Deploy All Lambdas Dynamically

on:
  push:
    branches: [ "main" ]

jobs:
  discover-lambdas:
    name: Discover Lambda Folders
    runs-on: ubuntu-latest
    outputs:
      folders-json: ${{ steps.lambdas.outputs.folders-json }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Find *-lambda directories under /project/*/
        id: lambdas
        run: |
          # Find folders like project/*/*-lambda
          dirs=$(find . -mindepth 2 -maxdepth 2 -type d -name '*-lambda' | sed 's|^\./||')

          arr=()
          for d in $dirs; do
            arr+=("\"$d\"")
          done
          json="[${arr[*]}]"
          json=$(echo "$json" | sed 's/ /,/g')

          echo "Found folders: $json"
          echo "folders-json=$json" >> $GITHUB_OUTPUT
          echo "::set-output name=folders-json::$json"

  build-and-deploy:
    name: Build and Deploy Each Lambda
    runs-on: ubuntu-latest
    needs: [ discover-lambdas ]
    environment: main
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.discover-lambdas.outputs.folders-json) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check if folder changed
        id: check_changes
        run: |
          if git diff --quiet HEAD~1 HEAD -- ${{ matrix.folder }}; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Build Lambda (if changed)
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          chmod +x build-lambda.sh
          ./build-lambda.sh ${{ matrix.folder }}

      - name: Configure AWS Credentials (if changed)
        if: steps.check_changes.outputs.changed == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda (if changed)
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          PROJECT=$(echo "${{ matrix.folder }}" | cut -d'/' -f1)
          LAMBDA_FOLDER=$(echo "${{ matrix.folder }}" | cut -d'/' -f2)
          FUNCTION_NAME="${PROJECT}-${LAMBDA_FOLDER}"

          echo "Deploying to Lambda: $FUNCTION_NAME"

          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://${{ matrix.folder }}/lambda.zip
