name: Deploy Shared Lambda Layer

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sinful-delights/shared/**'
      - '.github/workflows/deploy-shared-layer.yml'
      - 'build-shared-layer.sh'

jobs:
  deploy-shared-layer:
    name: Build and Deploy Shared Lambda Layer
    runs-on: ubuntu-latest
    environment: main
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check if shared folder changed
        id: check_shared_changes
        run: |
          if git diff --quiet HEAD~1 HEAD -- sinful-delights/shared/; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes in shared folder, skipping layer deployment"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in shared folder, will deploy layer"
          fi

      - name: Build Shared Layer (if changed)
        if: steps.check_shared_changes.outputs.changed == 'true'
        run: |
          chmod +x build-shared-layer.sh
          ./build-shared-layer.sh

      - name: Configure AWS Credentials (if changed)
        if: steps.check_shared_changes.outputs.changed == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Layer to AWS (if changed)
        if: steps.check_shared_changes.outputs.changed == 'true'
        id: deploy_layer
        run: |
          LAYER_NAME="sinful-delights-shared-layer"
          
          echo "Publishing Lambda Layer: $LAYER_NAME"
          
          # Publish the layer
          LAYER_VERSION=$(aws lambda publish-layer-version \
            --layer-name "$LAYER_NAME" \
            --description "Shared utilities and models for Sinful Delights API v$(date +%Y%m%d-%H%M%S)" \
            --license-info "MIT" \
            --compatible-runtimes python3.11 python3.10 python3.9 \
            --zip-file fileb://sinful-delights/shared-layer.zip \
            --query 'Version' \
            --output text)
          
          echo "Layer published successfully with version: $LAYER_VERSION"
          echo "layer_version=$LAYER_VERSION" >> $GITHUB_OUTPUT
          
          # Set layer permissions (optional - allows other accounts to use the layer)
          # aws lambda add-layer-version-permission \
          #   --layer-name "$LAYER_NAME" \
          #   --version-number "$LAYER_VERSION" \
          #   --statement-id "allow-account-access" \
          #   --principal "*" \
          #   --action "lambda:GetLayerVersion"

      - name: Update Layer Version in Repository
        if: steps.check_shared_changes.outputs.changed == 'true'
        run: |
          LAYER_VERSION="${{ steps.deploy_layer.outputs.layer_version }}"
          echo "SINFUL_DELIGHTS_SHARED_LAYER_VERSION=$LAYER_VERSION" > sinful-delights/.layer-version
          
          echo "Updated layer version file with version: $LAYER_VERSION"

      - name: Commit Layer Version Update
        if: steps.check_shared_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [[ -n $(git status --porcelain) ]]; then
            git add sinful-delights/.layer-version
            git commit -m "Update shared layer version to ${{ steps.deploy_layer.outputs.layer_version }}