name: Deploy All Lambdas Dynamically

on:
  push:
    branches: [ "main" ]

jobs:
  # First, ensure shared layer is deployed (for sinful-delights)
  check-shared-layer:
    name: Check Shared Layer Status
    runs-on: ubuntu-latest
    outputs:
      layer-version: ${{ steps.get_layer.outputs.version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get current layer version
        id: get_layer
        run: |
          if [ -f "sinful-delights/.layer-version" ]; then
            LAYER_VERSION=$(grep "SINFUL_DELIGHTS_SHARED_LAYER_VERSION=" sinful-delights/.layer-version | cut -d'=' -f2)
            echo "version=$LAYER_VERSION" >> $GITHUB_OUTPUT
            echo "Found shared layer version: $LAYER_VERSION"
          else
            echo "version=1" >> $GITHUB_OUTPUT
            echo "No layer version file found, using version 1"
          fi
  discover-lambdas:
    name: Discover Lambda Folders
    runs-on: ubuntu-latest
    outputs:
      folders-json: ${{ steps.lambdas.outputs.folders-json }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Find *-lambda directories under /project/*/
        id: lambdas
        run: |
          # Find folders like project/*/*-lambda
          dirs=$(find . -mindepth 2 -maxdepth 2 -type d -name '*-lambda' | sed 's|^\./||')

          arr=()
          for d in $dirs; do
            arr+=("\"$d\"")
          done
          json="[${arr[*]}]"
          json=$(echo "$json" | sed 's/ /,/g')

          echo "Found folders: $json"
          echo "folders-json=$json" >> $GITHUB_OUTPUT
          echo "::set-output name=folders-json::$json"

  build-and-deploy:
    name: Build and Deploy Each Lambda
    runs-on: ubuntu-latest
    needs: [ discover-lambdas, check-shared-layer ]
    environment: main
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.discover-lambdas.outputs.folders-json) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check if folder changed
        id: check_changes
        run: |
          if git diff --quiet HEAD~1 HEAD -- ${{ matrix.folder }}; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Build Lambda (if changed)
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          chmod +x build-lambda-with-layer.sh
          ./build-lambda-with-layer.sh ${{ matrix.folder }}

      - name: Configure AWS Credentials (if changed)
        if: steps.check_changes.outputs.changed == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda (if changed)
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          PROJECT=$(echo "${{ matrix.folder }}" | cut -d'/' -f1)
          LAMBDA_FOLDER=$(echo "${{ matrix.folder }}" | cut -d'/' -f2)
          FUNCTION_NAME="${PROJECT}-${LAMBDA_FOLDER}"
          LAYER_VERSION="${{ needs.check-shared-layer.outputs.layer-version }}"

          echo "Deploying to Lambda: $FUNCTION_NAME"

          # Update function code
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://${{ matrix.folder }}/lambda.zip

          # Update layers for sinful-delights functions
          if [ "$PROJECT" = "sinful-delights" ]; then
            echo "Updating Lambda layers for sinful-delights function..."
            
            # Get AWS Account ID dynamically if secret not available
            if [ -z "${{ secrets.AWS_ACCOUNT_ID }}" ]; then
              AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
              echo "Retrieved AWS Account ID: $AWS_ACCOUNT_ID"
            else
              AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}"
              echo "Using AWS Account ID from secret: $AWS_ACCOUNT_ID"
            fi
            
            LAYER_ARN="arn:aws:lambda:us-east-1:$AWS_ACCOUNT_ID:layer:sinful-delights-shared-layer:$LAYER_VERSION"
            
            aws lambda update-function-configuration \
              --function-name "$FUNCTION_NAME" \
              --layers "$LAYER_ARN" \
              --environment Variables="{PYTHONPATH=/opt/python}"
              
            echo "✓ Updated function to use shared layer version $LAYER_VERSION"
          else
            echo "Skipping layer update for non-sinful-delights function"
          fi
